### ISSUE TITLE
Feature Request: Adding a password to the zip 

### ISSUE THREAD

**Issue by aggjjfd** [vrtmrz/diffzip#3]
If i could add a password to the zip file by this plugin, it will secure the backup when I upload it to my cloud drive for safekeeping. Thank you!

**Comment by vrtmrz** [comment]
Thank you for opening the issue!
I think that this might be very useful! However, the library using this plug-in has [stated that it does not support it](https://github.com/101arrowz/fflate/issues/45). Other libraries are not so fast and do not have so much compatibility with Obsidian.

I regret to say that but this feature will not be implemented...
