### ISSUE TITLE
Does not work in Obsidian 1.6.3, Windows 10

### ISSUE THREAD

**Issue by merlinuwe** [vrtmrz/diffzip#4]
I just installed your plugin and at first sight, it seems to work.

![image](https://github.com/vrtmrz/diffzip/assets/4138869/0db825ce-58e2-4683-9954-57d23ea4c627)

But there is no file generated:

![image](https://github.com/vrtmrz/diffzip/assets/4138869/b45e50ad-38ec-40da-a2d8-d18e6856f317)

My settings:

`P:\000-Archiv\Obsidian.backups\DifferentialZIPBackup\backup`

``P:\000-Archiv\Obsidian.backups\DifferentialZIPBackup\restored

![image](https://github.com/vrtmrz/diffzip/assets/4138869/0c34928b-1af8-4f0d-8df3-b3dbecec9ca6)

This is the console output:

![image](https://github.com/vrtmrz/diffzip/assets/4138869/c544a9b4-b90b-454f-b12a-9bb387fa2ade)

SYSTEM INFO:
	Obsidian version: v1.6.3
	Installer version: v1.6.3
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.6.0
	Snippets enabled: 36
	Restricted mode: off
	Plugins installed: 149
	Plugins enabled: 56
		1: Set View Mode per Note v1.0.3
		2: Admonition v10.3.2
		3: Advanced Tables v0.21.0
		4: Advanced URI v1.40.1
		5: Android nomedia v0.1.0
		6: Auto Link Title v1.5.4
		7: Beautitab v1.6.1
		8: Better Export PDF v1.8.0
		9: Commander v0.5.1
		10: Colored Tags Wrangler v0.19.3
		11: Copy document as HTML v0.7.0
		12: Creases v0.7.0
		13: Custom Classes v2.6.1
		14: Dataview v0.5.67
		15: Dictionary v2.22.0
		16: Docxer v1.0.2
		17: Editing Toolbar v2.4.16
		18: Editor Commands Remap v1.0.2
		19: Editor Syntax Highlight v0.1.3
		20: Enhancing Export v1.10.6
		21: Excel to Markdown Table v0.4.0
		22: Export Image plugin v2.3.10
		23: File Explorer Note Count v1.2.2
		24: Google Calendar v1.10.14
		25: Linter v1.24.0
		26: Local Backup v0.1.7
		27: markdown export v1.0.21
		28: Natural Language Dates v0.6.2
		29: Navigate Cursor History v1.1.0
		30: Note Toolbar v1.7.28
		31: Number Headings v1.16.0
		32: Omnisearch v1.23.1
		33: Paste image rename v1.6.1
		34: Quick Explorer v0.2.8
		35: Quiet Outline v0.3.32
		36: Recent Files v1.4.1
		37: Scroll to Top v2.1.4
		38: Settings Management v1.0.5
		39: Sheet Plus v1.2.0
		40: Show Current File Path v0.5.2
		41: Sortable v0.3.1
		42: Status Bar Organizer v2.0.2
		43: Style Settings v1.0.8
		44: Supercharged Links v0.12.1
		45: Symbols Prettifier v1.1.2
		46: Tag Wrangler v0.6.1
		47: Tasks v7.4.0
		48: Templater v2.3.3
		49: Text Extractor v0.5.2
		50: Todo sort v1.0.0
		51: Translate v1.4.8
		52: Typing Transformer v0.4.0
		53: Vault Changelog v0.1.0
		54: Vault Statistics v0.1.3
		55: Webpage HTML Export v1.8.01
		56: Differential ZIP Backup v0.0.6

**Comment by vrtmrz** [comment]
Thank you for opening the issue! Unfortunately, the folder outside the vault has not been supported in previous versions.
However, I found it very useful, so I have implemented it as a desktop-only feature in v0.0.9. (It is pretty not a safe feature though, as it uses an internal API). 

Would you mind if I ask you to check the new feature, please?

**Comment by merlinuwe** [comment]
Testet soon, no output is created.

Here are some of the logs:

![image](https://github.com/vrtmrz/diffzip/assets/4138869/d7bdcb43-8fb1-4f79-83b4-ac688e2a8472)


![image](https://github.com/vrtmrz/diffzip/assets/4138869/14f7f019-2c7b-404b-9b26-6e705262cc3e)

![image](https://github.com/vrtmrz/diffzip/assets/4138869/bde00480-3ad3-4937-a45a-c8c871264377)

**Comment by merlinuwe** [comment]
Thank you very much. With release 0.0.10 underObsidian 1.6.7 the problem is solved. Is saves also on an external USB device.

Also, no error messages in the console anymore.
